version: '3.7'

services: 
  auth:
    image: joshuapn/auth
    build: 
      context: . 
  proxy:
    image: joshuapn/proxy
    build: 
      context: ./proxy
    ports: 
      - "8080:8080"
    depends_on: 
      - auth 
